baseURL = 'https://qingjrs.com/'
languageCode = 'zh-cn'
contentdir = 'content'
layoutdir = 'layouts'
builddrafts = false
title = '青椒肉丝-Qingjrs'
theme = 'PaperMod'

[[menu.main]]
  name = 'Home'
  weight = 1
  identifier = 'home'
  url = '/'
[[menu.main]]
  name = '归档'
  weight = 20
  url = '/archives/'
[[menu.main]]
  name = '目录'
  weight = 30
  url = '/categories/'
[[menu.main]]
  name = '标签'
  weight = 40
  url = '/tags/'

[params]
  author = 'Zeng Wenquan'
  defaultTheme = 'auto'
  # ShowShareButtons = true
  ShowReadingTime = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[taxonomies]
  category = 'categories'
  tag = 'tags'
