baseURL = './'
languageCode = 'zh-cn'
contentdir = 'content'
layoutdir = 'layouts'
title = '青椒肉丝-Qingjrs'
theme = 'PaperMod'
[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"